// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu-2aPrvhM-KxZC7SY7EHFfUlFswspvl0',
    appId: '1:1686148520:web:8e91206a50027140b3b99d',
    messagingSenderId: '1686148520',
    projectId: 'movie-app-3c03e',
    authDomain: 'movie-app-3c03e.firebaseapp.com',
    storageBucket: 'movie-app-3c03e.appspot.com',
    measurementId: 'G-KLYQ6XMZ46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP3vBYiA0HNsTomnaGoGlxDWt8C00WvwI',
    appId: '1:1686148520:android:a398c1eddd9650f4b3b99d',
    messagingSenderId: '1686148520',
    projectId: 'movie-app-3c03e',
    storageBucket: 'movie-app-3c03e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjrfcW1w7uwVtMzU0D9pXflDxzR9S_PhM',
    appId: '1:1686148520:ios:ec77783c9b876ffbb3b99d',
    messagingSenderId: '1686148520',
    projectId: 'movie-app-3c03e',
    storageBucket: 'movie-app-3c03e.appspot.com',
    iosBundleId: 'com.example.movie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjrfcW1w7uwVtMzU0D9pXflDxzR9S_PhM',
    appId: '1:1686148520:ios:ec77783c9b876ffbb3b99d',
    messagingSenderId: '1686148520',
    projectId: 'movie-app-3c03e',
    storageBucket: 'movie-app-3c03e.appspot.com',
    iosBundleId: 'com.example.movie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu-2aPrvhM-KxZC7SY7EHFfUlFswspvl0',
    appId: '1:1686148520:web:dc8b7206e018d08db3b99d',
    messagingSenderId: '1686148520',
    projectId: 'movie-app-3c03e',
    authDomain: 'movie-app-3c03e.firebaseapp.com',
    storageBucket: 'movie-app-3c03e.appspot.com',
    measurementId: 'G-X8MB29LZPJ',
  );
}
